version: '2'

services:
  frontend:
    build: frontend

  backend:
    build: backend
    depends_on: 
     - nats

  nats:
    image: nats

  proxy:
    build: proxy
    depends_on: 
     - backend
     - frontend
     - nats
    ports: 
     - 80:80